### ISSUE TITLE
CryptoNote compilation issues

### ISSUE THREAD

**Issue by Goro2030** [ProsusCorp/prosus#15]
During compilation and building of CryptoNote, we're getting a ton of "warning" . Let's try to know them down one at at time.

Starting with the most repetitive one, is this one:

```
 struct chacha8_key {
          ^~~~~~~~~~~
/prosus/cryptonote/src/CryptoNoteCore/Blockchain.cpp: In member function ‘bool CryptoNote::Blockchain::update_next_comulative_size_limit()’:
/prosus/cryptonote/src/CryptoNoteCore/Blockchain.cpp:1809:94: warning: ‘height’ is used uninitialized in this function [-Wuninitialized]

```

**Comment by prosus-money** [comment]
> ‘height’ is used uninitialized in this function

The new GNU compiler (on Ubuntu 19?) is who cares about those details. 

Meanwhile you can disable the warnings with a command, or modifying the warning level in the Makefile

**Comment by Goro2030** [comment]
Yes, it's Ubuntu 19 and latest GNU compiler. We should build always for the latest version of the compiler, so I recommend we refactor the code to include the initialization of the variable, or to force the ignore in the makefile

**Comment by Goro2030** [comment]
Closing issue as all of them have been solved by the new version posted today by @yerkobits
