### ISSUE TITLE
CryptoNote compilation warning #2 - Upgrade from memcpy

### ISSUE THREAD

**Issue by Goro2030** [ProsusCorp/prosus#16]
CryptoNote compilation warning #2 

```
/prosus/cryptonote/src/crypto/chacha8.h:48:40: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of non-trivially copyable type ‘struct Crypto::chacha8_key’; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
     memcpy(&key, &pwd_hash, sizeof(key));
                                        ^
```

**Comment by prosus-money** [comment]
new compiler issues to solve...
G++ ? std-C++ ? etc...
Do you recognize the compiler version you are using to build?

**Comment by Goro2030** [comment]
All the latest versions for Ubuntu 19 latest version ( installed it yesterday to do the compilation )

-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Boost version: 1.67.0

GNU Make 4.2.1
Built for x86_64-pc-linux-gnu

**Comment by Goro2030** [comment]
This errors just popup when just building CryptoNote's **OLDER** version. Current version that @yerkobits  posted today **do not generate any warnings**! When building the entire /prosus project, they do not show.

The **ONLY** warning in the Build is this:

> /prosus/src/NodeAdapter.cpp: In member function ‘bool WalletGui::NodeAdapter::init()’:
> /prosus/src/NodeAdapter.cpp:203:1: warning: control reaches end of non-void function [-Wreturn-type]
>  }
>  ^
> 

I think I can close this Issue then.
