### ISSUE TITLE
Connection issue in 0.7.2?

### ISSUE THREAD

**Issue by Goro2030** [ProsusCorp/prosus#17]
Downloaded and compiled 0.7.2, and now not being able to connect to any node:

```
019-Sep-20 08:09:11.896820 DEBUG   Selected peer: 7307302927830981033 18.221.201.1:18161 [white=1] last_seen: never
2019-Sep-20 08:09:11.897041 DEBUG   Connecting to 18.221.201.1:18161 (white=1, last_seen: never)...
2019-Sep-20 08:09:12.039358 DEBUG   Connection to 18.221.201.1:18161 failed: TcpConnector::connect, connection failed
2019-Sep-20 08:09:12.039480 DEBUG   Selected peer: 8770694130787931982 200.42.190.22:16180 [white=1] last_seen: never
2019-Sep-20 08:09:12.039516 DEBUG   Connecting to 200.42.190.22:16180 (white=1, last_seen: never)...
2019-Sep-20 08:09:17.040303 DEBUG   Connection to 200.42.190.22:16180 timed out, interrupt it
2019-Sep-20 08:09:17.040604 DEBUG   Connection timed out

```

Maybe a version compatibility issue, meaning my 0.7.2 client is newer or older than the other nodes' version? @yerkobits

**Comment by prosus-money** [comment]
> 18.221.201.1:18161

this is not a valid port, replace with...
**18.221.201.1:16180** 
or 
**18.221.201.1:16181**

**Comment by prosus-money** [comment]
> 200.42.190.22:16180 timed out

Maybe it's a outdated daemon or server is off (Prosus Corp not the owner)

**Comment by Goro2030** [comment]
Fucking dislexia ... thanks.

I had to ban  this node:
ban 200.72.65.134
Since he/she is using an older client version, and producing this:

> 2019-Sep-20 09:22:53.092260 INFO    Block with id: 45f0bf53105d05d0f8442b93fd8e0fe2b9f379a60d06485c92c161b6318847e1

When I ban it ... after a minute or two, it is "unbanned" . Why?

`2019-Sep-20 09:22:27.945059 INFO    Host 200.72.65.134 unblocked.`

**Comment by Goro2030** [comment]
Tring this now: 

`ban 200.72.65.134 999999999
`

**Comment by Goro2030** [comment]
Which is the command line parameter to set the number of CPU's to be used in mining?

**Comment by prosus-money** [comment]
> Which is the command line parameter to set the number of CPU's to be used in mining?

If daemon is running, type **_help_** to see commands...

  **stop_mining**     --> Stop mining

  **start_mining**    --> Start mining for specified address 

    start_mining <addr> [threads=1]

**Comment by Goro2030** [comment]
Not what I wanted to know @prosus-money  . @yerkobits told me to do <command> help, which gave me the answer. 

If using the prosus-daemon, the command is --mining-threads=x

Can one mine with a GPU?

**Comment by yerkobits** [comment]
> Can one mine with a GPU?

Only CPU, since 0.7.2 version (antiasic)
