### ISSUE TITLE
cmake + Qt5Gui

### ISSUE THREAD

**Issue by iamjuarez** [ProsusCorp/prosus#19]
**prosus/build$ cmake ..**
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Error at CMakeLists.txt:21 (find_package):
>   By not providing "FindQt5Gui.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5Gui", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5Gui" with any
>   of the following names:
> 
>    Qt5GuiConfig.cmake
>    qt5gui-config.cmake
> 
>   Add the installation prefix of "Qt5Gui" to CMAKE_PREFIX_PATH or set
>   "Qt5Gui_DIR" to a directory containing one of the above files.  If "Qt5Gui"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> -- Configuring incomplete, errors occurred!
>

**Comment by prosus-money** [comment]
sudo apt install qtbase5-dev

**Comment by yerkobits** [comment]
on Windows...
www.qt.io
(download and run, then install their MSVC packages)
