### ISSUE TITLE
libboost install 

### ISSUE THREAD

**Issue by iamjuarez** [ProsusCorp/prosus#21]
The boost1.67-dev alone does not work ... I did now download all 450 megabytes of libraries with:

`apt-get install libboost1.67-all-dev`

And it works... since I don't know which ones you use, cannot pick and choose the right ones...

_Originally posted by @Goro2030 in https://github.com/ProsusCorp/prosus/pull/18#issuecomment-533726285_

**Comment by iamjuarez** [comment]
installing especific libboost dependences for Cryptonote, one command line...

```
apt-get install -y \
libboost-dev \
libboost-regex-dev \
libboost-serialization-dev \
libboost-program-options-dev \
libboost-coroutine-dev \
libboost-context-dev \
libboost-system-dev \
libboost-filesystem-dev \
libboost-thread-dev \
libboost-date-time-dev \
libboost-chrono-dev 

```

**Comment by yerkobits** [comment]
> installing especific libboost dependences for Cryptonote, one command line...
> 
> ```
> apt-get install -y \
> libboost-dev \
> libboost-regex-dev \
> libboost-serialization-dev \
> libboost-program-options-dev \
> libboost-coroutine-dev \
> libboost-context-dev \
> libboost-system-dev \
> libboost-filesystem-dev \
> libboost-thread-dev \
> libboost-date-time-dev \
> libboost-chrono-dev 
> ```

**apt-get install libboost-all-dev**

many lines, more instructions = save disk space
just a line, simple instructions = no matters disk space

**Comment by Goro2030** [comment]
> apt-get install -y \
> libboost-dev \
> libboost-regex-dev \
> libboost-serialization-dev \
> libboost-program-options-dev \
> libboost-coroutine-dev \
> libboost-context-dev \
> libboost-system-dev \
> libboost-filesystem-dev \
> libboost-thread-dev \
> libboost-date-ti

I think this is the "correct" answer, not a long or a short one ... it's one "LONG" line, simpler instructions, and save disk space, as I proposed in the PULL for README.MD yesterday. It's libboost version independent, and works for everyone.

**Comment by Goro2030** [comment]
And I recommend you close this ISSUE, it's not an issue anymore

**Comment by iamjuarez** [comment]
https://github.com/ProsusCorp/prosus.money/pull/28#issue-444461217

**Comment by yerkobits** [comment]
ready on [BUILD.md](https://github.com/ProsusCorp/prosus.money/blob/master/BUILD.md)
> [#28 (comment)](https://github.com/ProsusCorp/prosus.money/pull/28#issue-444461217)
