### ISSUE TITLE
readme.md - Windows compile

### ISSUE THREAD

**Issue by iamjuarez** [ProsusCorp/prosus#22]
setting up the steps to compile in MS Windows

**Comment by Goro2030** [comment]
Oh! @yerkobits can do that ! :)

I remember I did this when wanting to try it, and it was not "as easy" :)

**Comment by yerkobits** [comment]
**Build on Windows** (test it many versions, please)

Dependencies: MSVC 2013 or later, CMake 2.8.6 or later, and Boost 1.55. You may download them from:
    http://www.microsoft.com/
    http://www.cmake.org/
    http://www.boost.org/

Open command line (cmd.exe), change to a directory where _CMakeList.txt_ file is located, and execute this:

mkdir build
cd build
cmake -G "Visual Studio 12 Win64" **..**
make

**Comment by iamjuarez** [comment]
https://github.com/ProsusCorp/prosus.money/pull/28#issue-444461217

**Comment by yerkobits** [comment]
moving to build.md ( #28 ) 

> 
> **Build on Windows** (test it many versions, please)
> 
> Dependencies: MSVC 2013 or later, CMake 2.8.6 or later, and Boost 1.55. You may download them from:
> http://www.microsoft.com/
> http://www.cmake.org/
> http://www.boost.org/
> 
> Open command line (cmd.exe), change to a directory where _CMakeList.txt_ file is located, and execute this:
> 
> mkdir build
> cd build
> cmake -G "Visual Studio 12 Win64" **..**
> make

**Comment by Goro2030** [comment]
Guys, it is confusing that the README.MD linked to the BUILD.MD for UBUNTU, both have references for it. That needs cleaning up... either move everything to that 2nd file (BUILD.MD) or leave Ubuntu's in README as I wrote it. @yerkobits  @iamjuarez

**Comment by yerkobits** [comment]
The text fragment on Readme.md is the **abstract**; the extensive text on Build.md is the **paper**.
Many projects on GitHub use this format, especially cross-compiling project (we use CMAKE files).

> Guys, it is confusing that the README.MD linked to the BUILD.MD for UBUNTU, both have references for it. That needs cleaning up... either move everything to that 2nd file (BUILD.MD) or leave Ubuntu's in README as I wrote it. @yerkobits @iamjuarez
