### ISSUE TITLE
Compiled Linux Wallet needs a default node IP to connect to

### ISSUE THREAD

**Issue by Goro2030** [ProsusCorp/prosus#27]
If I run the wallet with no parameters, it doesn't connect to any default node, therefore it fails to connect and create the wallet. The log looks like this:

```
2020-Jun-19 22:41:12.322363 INFO    prosus wallet v0.7.2 (antiasic)
Nor 'generate-new-wallet' neither 'wallet-file' argument was specified.
What do you want to do?
O - open wallet
G - generate new wallet
I - import wallet from keys
R - restore backup/paperwallet
T - import tracking wallet
E - exit
g
Specify wallet file name (e.g., wallet.bin).
Wallet file name: test
2020-Jun-19 22:41:15.558417 ERROR   Error: Error connecting to the remote node: TcpConnector::connect, connection failed
2020-Jun-19 22:41:15.561360 ERROR   Error: Failed to parse remote node response

```

We should add the default IP recommended for the daemon into the code.

**Comment by yerkobits** [comment]
The prosus-wallet must runs after prosus-daemon (local or remote daemon). Type `prosus-wallet --help` for details.
Mining with remote node is not allowed (the CPU instructions are local hardware).
(all Cryptonote clients work this way)
http://prosus.money/download

Only gui-wallet (not mining) connect automatically to a remote node if there no a local daemon.
