### ISSUE TITLE
Prosus Money 2021

### ISSUE THREAD

**Issue by prosus-money** [ProsusCorp/prosus#29]
I want to push [my repository](https://github.com/prosus-money/prosus-gui) but is different with the [official repository](https://github.com/prosuscorp/prosus.money) folders. Github does not give access to a merge
Please create / delete folders needed to perform the merge

**Comment by yerkobits** [comment]
I delete temporarily the folders...
* cryptonote
* libqrencode
* src

Now, you can create a directories in the official repository as a request.

**Comment by yerkobits** [comment]
I will create the directories in the official repository.

> 
> Now, you can create a directories in the official repository as a request.

**Comment by yerkobits** [comment]
I upload your repository here... 
Now, you can do a compatible request 😃

**Comment by prosus-money** [comment]
THANK YOU!

**Comment by Goro2030** [comment]
Not sure about what you did, but hope it works ... you can CLOSE this new.
