### ISSUE TITLE
Command line wallet reports balances incorrectly

### ISSUE THREAD

**Issue by Goro2030** [ProsusCorp/prosus#36]
All the calculations in the command line balance shows 10 times less coins than what it should... for example:

`2021-May-03 13:31:10.176613 INFO    available balance: 4940.824`

When in the GUI Windows wallet, it shows that I have 49408.24 coins

**Comment by yerkobits** [comment]
The release version (and its code) are fine.
https://github.com/ProsusCorp/prosus.money/releases

I'm going to close the issue.
