### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by iamjuarez** [ProsusCorp/prosus#7]
I like the idea behind Bytecoin, and apparently you have developed your own code from a Bytecoin fork. It is interesting to know that this project is an older cryptocurrency still working.
Can I support with some commits?

**Comment by yerkobits** [comment]
The project is alive. Outside of Github, we have developed a stable version (different from the one in this repository).
We would like the programmers to make their contributions to this current repository, before uploading the new version of Prosus-Money to Github.

**Comment by iamjuarez** [comment]
great! I found your website by chance, and your cryptocurrency called my attention for the fact of having more than 2 years without being in an exchange because its intention is a new economic model without a central bank, like the old bitcoin project. I'm going to check the code ;)

**Comment by Goro2030** [comment]
@yerkobits , you should put the "outside of Github" developed version IN GitHub, that's the very basic premise of transparency your Cryptocurrency should be based on. :)

**Comment by yerkobits** [comment]
> @yerkobits , you should put the "outside of Github" developed version IN GitHub, that's the very basic premise of transparency your Cryptocurrency should be based on. :)

[Prosus Money v0.7.2-gui](https://github.com/ProsusCorp/prosus/pull/14)
